version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: fern-fable-db
    environment:
      POSTGRES_DB: fern-fable
      POSTGRES_USER: fern
      POSTGRES_PASSWORD: fable
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: